Group Assignment 1


```{r}
# import Libraries
library(ggplot2)
library(dplyr)
```


```{r}
# load data
df <- read.csv('C:\\Users\\Kiersten\\Documents\\School\\Session_4\\Alistair\\MarketDataMonopoly.csv')
str(df)
```

```{r}
# profit
df$Profit <- df$Revenue - df$Cost
```


```{r}
ggplot(df, aes(x=InputCostIndex, y=Production)) +
      geom_point()

ggplot(df, aes(x=DemandIndex, y=Production)) +
      geom_point()
```

```{r}
# outcome
reg <- lm(Production ~ InputCostIndex + DemandIndex, df)
summary(reg)
```

```{r}
ggplot(df, aes(x=InputCostIndex, y=Cost)) +
      geom_point()

ggplot(df, aes(x=Production, y=Cost)) +
      geom_point()
```

```{r}
# cost model
model1 <- lm(Cost ~ Production + InputCostIndex, df)
summary(model1)
```


```{r}
# price 
df$Price <- df$Revenue/df$Production

ggplot(df, aes(x=DemandIndex, y=Price)) +
      geom_point()

ggplot(df, aes(x=Production, y=Price)) +
      geom_point()
```

```{r}
# price model
model2 <- lm(Price ~ Production + DemandIndex, df)
summary(model2)
```

```{r}
# predict
# new df
input <- data.frame('InputCostIndex' = c(100, 200, 50), 'DemandIndex' = c(10, 5, 17), 'Production' = c(0, 0, 0), 'Cost' = c(0, 0, 0), 'Price' = c(0, 0, 0), 'Profit' = c(0, 0, 0))

for (i in 1:3){
  # production
  input[i, 3] = predict(reg, newdata = input[i,])
  # cost
  input[i, 4] = predict(model1, newdata = input[i,])
  # demand
  input[i, 5] = predict(model2, newdata = input[i,])
  # profit
  input[i, 6] = input[i, 3]*input[i, 5]-input[i, 4]
}

input
```

```{r}
newton.rhapson.fullnumeric<-function(f,x0,tol=1e-8,eps=1e-6,maxiter=50,output=FALSE) {
    # argumens: f: function to optimize, x0: initial guess
    xx=x0
    #This is our equation for the derivative
    fval=num.deriv.1(f,xx,eps)
    Error=abs(fval)
    ii=1
    # Repeat the steps until the error is less than the tolerance
    while (Error>tol & ii <maxiter ){
        # this is our equation for the second derivative
        fd=num.deriv.2( f , xx, sqrt(eps) )
        # So this is the Newton-rhapson step for
        # solving the derivative root
        # via x1=x0-f'(x0)/f"(x0)
        xx=xx-fval/fd
        fval=num.deriv.1(f,xx,eps)
        Error=abs(fval)
        ii=ii+1
    } 
    if (ii>=maxiter) print("Exited due to non-convergence")        
    if (output && ii<maxiter ) print(paste("Converged to solution ",  toString(round(xx,digits=5))," in ", toString(ii-1)," steps"))
    xx
}
```

```{r}
profit <- function(CostIndex, DemandIndex) {
    (2.523e+00 - 9.095e-02*CostIndex + 4.477e+00*DemandIndex)*(10.508292 - 0.260320*(2.523e+00 - 9.095e-02*CostIndex + 4.477e+00*DemandIndex) + 2.937987*DemandIndex) - (3.040e+02 + 1.975e+01*(2.523e+00 - 9.095e-02*CostIndex + 4.477e+00*DemandIndex) + 1.536e+00*CostIndex)
  }
```



```{r}
newton.rhapson.fullnumeric(f2,4) #global minima
newton.rhapson.fullnumeric(f2,-1) #local minima
newton.rhapson.fullnumeric(f2,1) #local maxima
```


```{r}
predict_function <- function(CostIndex, DemandIndex){
  production <- 2.523e+00 - 9.095e-02*CostIndex + 4.477e+00*DemandIndex
  cost <- -3.040e+02 + 1.975e+01*production + 1.536e+00*CostIndex
  price <- 10.508292 - 0.260320*production + 2.937987*DemandIndex
  profit <- production*price - cost
  
  output <- data.frame('Production' = production, 'Cost' = cost, 'Profit' = profit)
  print(output)
}
```



```{r}
predict_function(100,10)
predict_function(200,5)
predict_function(50,17)
```




